
spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://thingsillove-db-server.cqg41lvwng6q.ap-northeast-2.rds.amazonaws.com/thingsilove
      driver-class-name: org.mariadb.jdbc.Driver
      username: ugo
      password: AsdAsd12!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
  servlet:
    session:
      cookie:
        same-site: lax
        secure: true
        max-age: 30m
